import { createClient } from '@/lib/supabase/server'
import { notFound, redirect } from 'next/navigation'
import Link from 'next/link'
import CopyLink from '@/components/dashboard/CopyLink'
import CreateProposalForm from '@/components/dashboard/CreateProposalForm'
import { ClientStatus } from '@/types/database'

const statusConfig: Record<ClientStatus, { label: string; color: string }> = {
  pending_brief: { label: 'Awaiting brief', color: 'bg-yellow-100 text-yellow-800' },
    brief_submitted: { label: 'Brief received', color: 'bg-blue-100 text-blue-800' },
      proposal_sent: { label: 'Proposal sent', color: 'bg-purple-100 text-purple-800' },
        proposal_approved: { label: 'Approved', color: 'bg-green-100 text-green-800' },
          completed: { label: 'Completed', color: 'bg-gray-100 text-gray-800' },
          }

          export default async function ClientDetailPage({ params }: { params: Promise<{ id: string }> }) {
            const { id } = await params
              const supabase = await createClient()
                const { data: { user } } = await supabase.auth.getUser()
                  if (!user) redirect('/login')
                    const { data: client } = await supabase.from('clients').select('*').eq('id', id).eq('designer_id', user!.id).single()
                      if (!client) notFound()
                        const { data: brief } = await supabase.from('briefs').select('*').eq('client_id', id).order('submitted_at', { ascending: false }).limit(1).maybeSingle()
                          const { data: proposal } = await supabase.from('proposals').select('*').eq('client_id', id).order('created_at', { ascending: false }).limit(1).maybeSingle()
                            const appUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://brieframp.com'
                              const briefUrl = `${appUrl}/brief/${client!.brief_token}`
                                const status = statusConfig[client!.status as ClientStatus]
                                  return (
                                      <div className="max-w-3xl">
                                            <div className="mb-8">
                                                    <Link href="/dashboard" className="text-sm text-gray-500 hover:text-gray-900 mb-4 inline-block">← Back to dashboard</Link>
                                                            <div className="flex items-center justify-between">
                                                                      <div><h1 className="text-2xl font-bold text-gray-900">{client!.name}</h1><p className="text-gray-500 text-sm mt-1">{client!.email}</p></div>
                                                                                <span className={`px-3 py-1 rounded-full text-xs font-medium ${status.color}`}>{status.label}</span>
                                                                                        </div>
                                                                                              </div>
                                                                                                    <div className="bg-white rounded-xl border border-gray-200 p-6 mb-6">
                                                                                                            <h2 className="font-semibold text-gray-900 mb-1">Brief link</h2>
                                                                                                                    <p className="text-sm text-gray-500 mb-4">Share this link with your client to collect their brief</p>
                                                                                                                            <CopyLink url={briefUrl} />
                                                                                                                                  </div>
                                                                                                                                        {brief ? (
                                                                                                                                                <div className="bg-white rounded-xl border border-gray-200 p-6 mb-6">
                                                                                                                                                          <h2 className="font-semibold text-gray-900 mb-4">Brief submitted</h2>
                                                                                                                                                                    <div className="space-y-4">
                                                                                                                                                                                {brief.project_type && <Field label="Project type" value={brief.project_type} />}
                                                                                                                                                                                            {brief.description && <Field label="Description" value={brief.description} />}
                                                                                                                                                                                                        {brief.budget_range && <Field label="Budget" value={brief.budget_range} />}
                                                                                                                                                                                                                    {brief.timeline && <Field label="Timeline" value={brief.timeline} />}
                                                                                                                                                                                                                                {brief.pages && <Field label="Pages" value={brief.pages} />}
                                                                                                                                                                                                                                            {brief.branding_notes && <Field label="Branding notes" value={brief.branding_notes} />}
                                                                                                                                                                                                                                                        {brief.examples && <Field label="Examples" value={brief.examples} />}
                                                                                                                                                                                                                                                                    {brief.additional_info && <Field label="Additional info" value={brief.additional_info} />}
                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                        {!proposal && <div className="mt-6 pt-6 border-t border-gray-100"><h3 className="font-semibold text-gray-900 mb-4">Create proposal</h3><CreateProposalForm clientId={client!.id} /></div>}
                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                              <div className="bg-white rounded-xl border border-gray-200 p-6 mb-6 text-center py-12"><p className="text-2xl mb-3">📋</p><p className="text-gray-600 font-medium">No brief yet</p><p className="text-gray-500 text-sm mt-1">Share the link above with your client</p></div>
                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                          {proposal && (
                                                                                                                                                                                                                                                                                                                                  <div className="bg-white rounded-xl border border-gray-200 p-6">
                                                                                                                                                                                                                                                                                                                                            <div className="flex items-center justify-between mb-4"><h2 className="font-semibold text-gray-900">Proposal</h2><span className={`px-2.5 py-1 rounded-full text-xs font-medium ${proposal.status === 'approved' ? 'bg-green-100 text-green-800' : proposal.status === 'rejected' ? 'bg-red-100 text-red-800' : 'bg-gray-100 text-gray-800'}`}>{proposal.status}</span></div>
                                                                                                                                                                                                                                                                                                                                                      <Field label="Title" value={proposal.title} />
                                                                                                                                                                                                                                                                                                                                                                <div className="mt-3"><Field label="Price" value={`$${proposal.price} ${proposal.currency}`} /></div>
                                                                                                                                                                                                                                                                                                                                                                          {(proposal.status === 'draft' || proposal.status === 'sent') && <div className="mt-4 pt-4 border-t border-gray-100"><p className="text-sm text-gray-500 mb-2">Proposal link:</p><CopyLink url={`${appUrl}/proposal/${proposal.proposal_token}`} /></div>}
                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                              function Field({ label, value }: { label: string; value: string }) {
                                                                                                                                                                                                                                                                                                                                                                                                return (<div><p className="text-xs font-medium text-gray-500 uppercase tracking-wide">{label}</p><p className="text-sm text-gray-900 mt-0.5 whitespace-pre-wrap">{value}</p></div>)
                                                                                                                                                                                                                                                                                                                                                                                                }